// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqjvatesderypegoxnqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxanZhdGVzZGVyeXBlZ294bnF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQwNDMyODIsImV4cCI6MjA4OTYxOTI4Mn0.7OFCVxDTK4Vtxed_72yHxwL_m4nrT_p9SFBiU6Qx4u0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});